# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
-  script:
     docker build -f Dockerfile -t foobar.azurecr.io/hello:world .
-  script: 
     docker run foobar.azurecr.io/hello:world